name: Deploy to OCI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_NAME: ${{ env.DB_NAME }}
          DB_USERNAME: ${{ env.DB_USERNAME }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}

      - name: Copy Files to OCI Instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.OCI_INSTANCE_IP }}
          username: ${{ secrets.OCI_INSTANCE_USERNAME }}
          key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
          source: .  # Puede ser necesario ajustar la ruta de origen según tu estructura de directorios
          target: /AppServicioSalud
